### PR TITLE
Add test code from java_common

### PR DESCRIPTION
**Pull request by MrCreosote**
When packing java_common from jitpack.io, only the code in main/java is packed, (which makes sense) which doesn't include any of the code here. Moving the test halper code to main/java would mean that junit and hamcrest would now be in the runtime classpath, which we don't want, so it seems the least bad option is to make a new library.

Also copied over the blobstore and minio controllers from workspace. The mysql controller is unused to my knowledge so it was not copied.

### CODE REVIEW

**Comment by Xiangs18** [comment]
In blobstore repo, there were also a bunch of controllers: https://github.com/kbase/blobstore/tree/develop/test.
Do they serve different purposes?

**Comment by Xiangs18** [comment]
Also, I am not sure why we need @SuppressWarnings("unused") in all noop(). Because `foo` is unused?
I ran `gradle build` with and without @SuppressWarnings("unused"), I did not see any difference. Am I missing something?

**Comment by MrCreosote** [comment]
> In blobstore repo, there were also a bunch of controllers

* Mongo is in this repo
* Minio is in the workspace repo because that's the only java service that uses it. If more services start using it we should move it here
* Auth lives in the auth repo

**Comment by MrCreosote** [comment]
> Also, I am not sure why we need @SuppressWarnings("unused") 

It prevents IDEs from complaining about unused variables. There's also probably some way to get Gradle to report out on compile warnings, but I guess by default it doesn't

**Review by Xiangs18 — APPROVED** [review]
LGTM!

**Pull request merged**
